#!/bin/sh

git clone https://github.com/vim-airline/vim-airline ~/.vim/bundle/vim-airline --recursive --depth 1
git clone http://github.com/vim-airline/vim-airline-themes  ~/.vim/bundle/vim-airline-themes --recursive --depth 1
git clone http://github.com/mbbill/undotree ~/.vim/bundle/undotree --recursive --depth 1
git clone http://github.com/mhinz/vim-startify ~/.vim/bundle/vim-startify --recursive --depth 1
git clone http://github.com/ctrlpvim/ctrlp.vim ~/.vim/bundle/ctrlp.vim --recursive --depth 1
git clone http://github.com/kh3phr3n/python-syntax ~/.vim/bundle/python-syntax --recursive --depth 1
git clone http://github.com/VundleVim/Vundle.vim ~/.vim/bundle/Vundle.vim --recursive --depth 1
git clone http://github.com/scrooloose/nerdtree ~/.vim/bundle/nerdtree --recursive --depth 1
git clone http://github.com/sickill/vim-pasta ~/.vim/bundle/vim-pasta --recursive --depth 1
git clone http://github.com/adelarsq/vim-matchit  ~/.vim/bundle/vim-matchit --recursive --depth 1
git clone http://github.com/makerj/vim-pdf ~/.vim/bundle/vim-pdf --recursive --depth 1
git clone http://github.com/Xuyuanp/nerdtree-git-plugin ~/.vim/bundle/nerdtree-git-plugin --recursive --depth 1
git clone http://github.com/vim-ctrlspace/vim-ctrlspace ~/.vim/bundle/vim-ctrlspace --recursive --depth 1
git clone http://github.com/mhinz/vim-signify ~/.vim/bundle/vim-signify --recursive --depth 1
git clone http://github.com/octol/vim-cpp-enhanced-highlight ~/.vim/bundle/vim-cpp-enhanced-highlight --recursive --depth 1
git clone http://github.com/vimwiki/vimwiki ~/.vim/bundle/vimwiki --recursive --depth 1
git clone http://github.com/flazz/vim-colorschemes ~/.vim/bundle/vim-colorschemes --recursive --depth 1
git clone http://github.com/plasticboy/vim-markdown ~/.vim/bundle/vim-markdown --recursive --depth 1
git clone http://github.com/neomutt/neomutt.vim ~/.vim/bundle/neomutt.vim --recursive --depth 1
git clone http://github.com/sngn/vim-i3blocks-syntax ~/.vim/bundle/vim-i3blocks-syntax --recursive --depth 1
git clone http://github.com/rhysd/vim-wasm ~/.vim/bundle/vim-wasm --recursive --depth 1
git clone http://github.com/nathanaelkane/vim-indent-guides ~/.vim/bundle/vim-indent-guides --recursive --depth 1
git clone http://github.com/tomlion/vim-solidity ~/.vim/bundle/vim-solidity --recursive --depth 1
git clone http://github.com/dense-analysis/ale ~/.vim/bundle/ale --recursive --depth 1
git clone http://github.com/ekalinin/Dockerfile.vim ~/.vim/bundle/Dockerfile.vim --recursive --depth 1
git clone http://github.com/PotatoesMaster/i3-vim-syntax ~/.vim/bundle/i3-vim-syntax --recursive --depth 1
git clone http://github.com/chrisbra/NrrwRgn ~/.vim/bundle/NrrwRgn --recursive --depth 1
git clone http://github.com/kana/vim-arpeggio ~/.vim/bundle/vim-arpeggio --recursive --depth 1
git clone http://github.com/easymotion/vim-easymotion ~/.vim/bundle/vim-easymotion --recursive --depth 1
git clone http://github.com/neovimhaskell/haskell-vim ~/.vim/bundle/haskell-vim --recursive --depth 1
git clone http://github.com/majutsushi/tagbar ~/.vim/bundle/tagbar --recursive --depth 1
git clone http://github.com/szw/vim-maximizer ~/.vim/bundle/vim-maximizer --recursive --depth 1
git clone http://github.com/chrisbra/csv.vim ~/.vim/bundle/csv.vim --recursive --depth 1
git clone http://github.com/Valloric/YouCompleteMe ~/.vim/bundle/YouCompleteMe --recursive --depth 1
git clone http://github.com/vim-pandoc/vim-pandoc ~/.vim/bundle/vim-pandoc --recursive --depth 1
git clone http://github.com/vim-pandoc/vim-pandoc-syntax ~/.vim/bundle/vim-pandoc-syntax --recursive --depth 1
git clone http://github.com/elzr/vim-json ~/.vim/bundle/vim-json --recursive --depth 1
git clone http://github.com/wellle/context.vim ~/.vim/bundle/context.vim --recursive --depth 1
git clone http://github.com/ludovicchabant/vim-gutentags ~/.vim/bundle/vim-gutentags --recursive --depth 1
git clone http://github.com/skywind3000/gutentags_plus ~/.vim/bundle/gutentags_plus --recursive --depth 1
git clone http://github.com/stephpy/vim-yaml ~/.vim/bundle/vim-yaml --recursive --depth 1
git clone http://github.com/unblevable/quick-scope ~/.vim/bundle/quick-scope --recursive --depth 1
git clone http://github.com/SirVer/ultisnips ~/.vim/bundle/ultisnips --recursive --depth 1
git clone http://github.com/honza/vim-snippets ~/.vim/bundle/vim-snippets --recursive --depth 1
git clone http://github.com/chrisbra/Recover.vim ~/.vim/bundle/Recover.vim --recursive --depth 1
git clone http://github.com/wellle/targets.vim ~/.vim/bundle/targets.vim --recursive --depth 1
git clone http://github.com/rhysd/git-messenger.vim ~/.vim/bundle/git-messenger.vim --recursive --depth 1
git clone http://github.com/mhinz/vim-grepper ~/.vim/bundle/vim-grepper --recursive --depth 1
git clone http://github.com/vim-utils/vim-troll-stopper ~/.vim/bundle/vim-troll-stopper --recursive --depth 1
git clone http://github.com/junegunn/limelight.vim ~/.vim/bundle/limelight.vim --recursive --depth 1
git clone http://github.com/valloric/MatchTagAlways ~/.vim/bundle/MatchTagAlways --recursive --depth 1
git clone http://github.com/junegunn/vim-peekaboo ~/.vim/bundle/vim-peekaboo --recursive --depth 1
git clone http://github.com/tpope/vim-vinegar ~/.vim/bundle/vim-vinegar --recursive --depth 1
git clone http://github.com/tpope/vim-commentary ~/.vim/bundle/vim-commentary --recursive --depth 1
git clone http://github.com/tpope/vim-rhubarb ~/.vim/bundle/vim-rhubarb --recursive --depth 1
git clone http://github.com/rgrinberg/vim-ocaml ~/.vim/bundle/vim-ocaml --recursive --depth 1
git clone http://github.com/terryma/vim-multiple-cursors ~/.vim/bundle/vim-multiple-cursors --recursive --depth 1
git clone http://github.com/kshenoy/vim-signature ~/.vim/bundle/vim-signature --recursive --depth 1
git clone http://github.com/Konfekt/vim-scratchpad ~/.vim/bundle/vim-scratchpad --recursive --depth 1
git clone http://github.com/tmux-plugins/vim-tmux ~/.vim/bundle/vim-tmux --recursive --depth 1
git clone http://github.com/rust-lang/rust.vim ~/.vim/bundle/rust.vim --recursive --depth 1
git clone http://github.com/tpope/vim-repeat ~/.vim/bundle/vim-repeat --recursive --depth 1
git clone http://github.com/cespare/vim-toml ~/.vim/bundle/vim-toml --recursive --depth 1
git clone http://github.com/maralla/vim-toml-enhance ~/.vim/bundle/vim-toml-enhance --recursive --depth 1
git clone http://github.com/junegunn/fzf ~/.vim/bundle/fzf --recursive --depth 1
git clone http://github.com/junegunn/fzf.vim ~/.vim/bundle/fzf.vim --recursive --depth 1
git clone http://github.com/jelera/vim-javascript-syntax ~/.vim/bundle/vim-javascript-syntax --recursive --depth 1
git clone http://github.com/chiel92/vim-autoformat ~/.vim/bundle/vim-autoformat --recursive --depth 1
git clone http://github.com/vim-scripts/ZoomWin ~/.vim/bundle/ZoomWin --recursive --depth 1
git clone http://github.com/wakatime/vim-wakatime ~/.vim/bundle/vim-wakatime --recursive --depth 1
git clone http://github.com/terryma/vim-expand-region ~/.vim/bundle/vim-expand-region --recursive --depth 1
git clone http://github.com/tpope/vim-surround ~/.vim/bundle/vim-surround --recursive --depth 1
git clone http://github.com/vim-scripts/DoxyGen-Syntax ~/.vim/bundle/DoxyGen-Syntax --recursive --depth 1
git clone http://github.com/vim-scripts/DoxygenToolkit.vim ~/.vim/bundle/DoxygenToolkit.vim --recursive --depth 1
git clone http://github.com/szymonmaszke/vimpyter ~/.vim/bundle/vimpyter --recursive --depth 1
git clone http://github.com/fatih/vim-go ~/.vim/bundle/vim-go --recursive --depth 1
git clone http://github.com/tpope/vim-fugitive ~/.vim/bundle/vim-fugitive --recursive --depth 1
git clone http://github.com/junegunn/goyo.vim ~/.vim/bundle/goyo.vim --recursive --depth 1
git clone http://github.com/amix/vim-zenroom2 ~/.vim/bundle/vim-zenroom2 --recursive --depth 1
git clone http://github.com/raimon49/requirements.txt.vim ~/.vim/bundle/requirements.txt.vim --recursive --depth 1
git clone http://github.com/Shougo/vimproc.vim ~/.vim/bundle/vimproc.vim --recursive --depth 1
git clone http://github.com/rhysd/vim-llvm ~/.vim/bundle/vim-llvm --recursive --depth 1
git clone http://github.com/rhysd/vim-gfm-syntax ~/.vim/bundle/vim-gfm-syntax --recursive --depth 1
git clone http://github.com/haya14busa/is.vim ~/.vim/bundle/is.vim --recursive --depth 1
git clone http://github.com/haya14busa/vim-asterisk ~/.vim/bundle/vim-asterisk --recursive --depth 1
git clone http://github.com/haya14busa/incsearch.vim ~/.vim/bundle/incsearch.vim --recursive --depth 1
git clone http://github.com/haya14busa/vim-edgemotion ~/.vim/bundle/vim-edgemotion --recursive --depth 1
git clone http://github.com/lervag/vimtex ~/.vim/bundle/vimtex --recursive --depth 1
git clone http://github.com/vim-utils/vim-man ~/.vim/bundle/vim-man --recursive --depth 1
git clone http://github.com/ajh17/VimCompletesMe ~/.vim/bundle/VimCompletesMe --recursive --depth 1
git clone http://github.com/ryanoasis/vim-devicons ~/.vim/bundle/vim-devicons --recursive --depth 1
git clone http://github.com/sheerun/vim-polyglot ~/.vim/bundle/vim-polyglot --recursive --depth 1
